version: "1"
services:
  mysql:
    image: my_mysql:latest
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=arteta
      - MYSQL_DATABASE=arsenal
      - MYSQL_USER=saka
      - MYSQL_PASSWORD=hattrick
        # env_file:
        # - ./variables.env

