FROM debian:bullseye

RUN mkdir /host_os
RUN apt update -y

COPY file.sh /host_os
COPY nginx.conf /etc/nginx/conf.d/

RUN chmod +x /host_os/file.sh && ./host_os/file.sh

CMD ["nginx", "-g", "daemon off;"]